-- =========================================================================
-- 인사장(Insajang) 데이터베이스 스키마 생성 스크립트 (schema.sql)
-- =========================================================================

-- 1. 기존 테이블 삭제 (초기화 빌드 목적 - 안전장치)
DROP TABLE IF EXISTS public.files CASCADE;
DROP TABLE IF EXISTS public.contents CASCADE;
DROP TABLE IF EXISTS public.content_logs CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.refresh_tokens CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- 2. users 테이블 생성
CREATE TABLE public.users (
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(100) NOT NULL,
    name character varying(13) NOT NULL,
    nickname character varying(13) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    email_on_publish character varying(1) DEFAULT 'Y'::character varying NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT uk_users_nickname UNIQUE (nickname),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- 3. projects 테이블 생성
CREATE TABLE public.projects (
    project_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    description text,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT projects_pkey PRIMARY KEY (project_id),
    CONSTRAINT fk_projects_users FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);

-- 4. content_logs 테이블 생성
CREATE TABLE public.content_logs (
    log_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content_type character varying(50),
    created_at timestamp(6) without time zone,
    generated_body text NOT NULL,
    project_id bigint,
    title character varying(255),
    type character varying(255),
    user_id bigint NOT NULL,
    user_input text,
    CONSTRAINT content_logs_pkey PRIMARY KEY (log_id),
    CONSTRAINT content_logs_projects_fk FOREIGN KEY (project_id) REFERENCES public.projects(project_id) ON DELETE SET NULL,
    CONSTRAINT content_logs_users_fk FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL
);

-- 5. contents 테이블 생성
CREATE TABLE public.contents (
    content_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    body text NOT NULL,
    content_type character varying(50),
    created_at timestamp(6) without time zone,
    log_id bigint,
    project_id bigint,
    scheduled_at timestamp(6) without time zone,
    status character varying(50),
    title character varying(255),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    user_input text,
    verification_token character varying(255),
    token_generated_at timestamp without time zone,
    CONSTRAINT contents_pkey PRIMARY KEY (content_id),
    CONSTRAINT contents_projects_fk FOREIGN KEY (project_id) REFERENCES public.projects(project_id) ON DELETE CASCADE,
    CONSTRAINT contents_users_fk FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);

-- 6. files 테이블 생성
CREATE TABLE public.files (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    extension character varying(10) NOT NULL,
    file_path character varying(500) NOT NULL,
    file_size bigint,
    original_name character varying(255),
    saved_name character varying(255) NOT NULL,
    status character varying(20),
    updated_at timestamp(6) without time zone,
    content_id bigint,
    log_id bigint NOT NULL,
    CONSTRAINT files_pkey PRIMARY KEY (id),
    CONSTRAINT fk_files_contents FOREIGN KEY (content_id) REFERENCES public.contents(content_id) ON DELETE SET NULL,
    CONSTRAINT fk_files_content_logs FOREIGN KEY (log_id) REFERENCES public.content_logs(log_id) ON DELETE SET NULL
);

-- 7. refresh_tokens 테이블 생성
CREATE TABLE public.refresh_tokens (
    refresh_token_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    token character varying(500) NOT NULL,
    user_id bigint NOT NULL,
    expiry_date timestamp without time zone NOT NULL,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (refresh_token_id),
    CONSTRAINT refresh_tokens_token_key UNIQUE (token)
);
