# --------------------------------------------------
# \uB370\uC774\uD130\uBCA0\uC774\uC2A4(DB) \uC5F0\uACB0 \uC124\uC815
# --------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/insajang
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# --------------------------------------------------
# JPA \uBC0F \uD558\uC774\uBC84\uB124\uC774\uD2B8(Hibernate) \uC124\uC815
# --------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.orm.jdbc.bind=trace

# --------------------------------------------------
# Facebook OAuth2 \uC5F0\uB3D9 \uC124\uC815
# --------------------------------------------------
# \uBA54\uD0C0 \uC571 ID \uBC0F \uC2DC\uD06C\uB9BF
spring.security.oauth2.client.registration.facebook.client-id=897001629339114
spring.security.oauth2.client.registration.facebook.client-secret=4608caa3cd85670920243361968d6ef9


spring.security.oauth2.client.registration.facebook.scope=public_profile

# \uB9AC\uB2E4\uC774\uB809\uD2B8 \uC8FC\uC18C
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/facebook