# --------------------------------------------------
# \uB370\uC774\uD130\uBCA0\uC774\uC2A4(DB) \uC5F0\uACB0 \uC124\uC815
# --------------------------------------------------
# DB \uC811\uC18D \uC8FC\uC18C (\uD3EC\uD2B8\uC640 DB\uC774\uB984 \uD655\uC778!)
spring.datasource.url=jdbc:postgresql://localhost:5432/insajang
# DB \uC811\uC18D \uACC4\uC815 (\uAE30\uBCF8\uAC12: postgres)
spring.datasource.username=postgres
# DB \uC811\uC18D \uBE44\uBC00\uBC88\uD638
spring.datasource.password=1234
# DB \uB4DC\uB77C\uC774\uBC84 \uC124\uC815 (PostgreSQL\uC6A9)
spring.datasource.driver-class-name=org.postgresql.Driver

# --------------------------------------------------
# JPA \uBC0F \uD558\uC774\uBC84\uB124\uC774\uD2B8(Hibernate) \uC124\uC815
# --------------------------------------------------
# \uD14C\uC774\uBE14 \uC790\uB3D9 \uC0DD\uC131 \uC124\uC815
# (update: \uC790\uBC14 \uD074\uB798\uC2A4 \uBCC0\uACBD \uC2DC DB\uC5D0 \uBC18\uC601 / create: \uC11C\uBC84 \uCF24 \uB54C\uB9C8\uB2E4 \uD14C\uC774\uBE14 \uCD08\uAE30\uD654)
spring.jpa.hibernate.ddl-auto=update

# \uC2E4\uD589\uB418\uB294 SQL\uBB38\uC744 \uCF58\uC194\uCC3D(\uB85C\uADF8)\uC5D0 \uCD9C\uB825\uD560\uC9C0 \uC5EC\uBD80
spring.jpa.show-sql=true

# \uCF58\uC194\uC5D0 \uCD9C\uB825\uB418\uB294 SQL\uBB38\uC744 \uBCF4\uAE30 \uC88B\uAC8C \uD3EC\uB9F7\uD305
spring.jpa.properties.hibernate.format_sql=true

# SQL\uBB38\uC5D0 \uC8FC\uC11D\uC744 \uCD94\uAC00\uD574\uC11C \uC5B4\uB514\uC11C \uC2E4\uD589\uB41C \uAC74\uC9C0 \uD45C\uC2DC
spring.jpa.properties.hibernate.use_sql_comments=true