# --------------------------------------------------
# \uB370\uC774\uD130\uBCA0\uC774\uC2A4(DB) \uC5F0\uACB0 \uC124\uC815
# --------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/insajang
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# --------------------------------------------------
# JPA \uBC0F \uD558\uC774\uBC84\uB124\uC774\uD2B8(Hibernate) \uC124\uC815
# --------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.orm.jdbc.bind=trace

# \uBA54\uC77C \uC11C\uBC84 \uC124\uC815 (Gmail \uAE30\uC900)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#\uD504\uB85C\uC81D\uD2B8 \uC804\uC6A9 \uBCC0\uC218 (\uD558\uB4DC\uCF54\uB529 \uBC29\uC9C0\uC6A9)
app.frontend-url=${APP_FRONTEND_URL:http://localhost:3000}
app.backend-url=${APP_BACKEND_URL:http://localhost:8080}
app.python-url=${APP_PYTHON_URL:http://localhost:8000}

# \uD30C\uC77C \uC5C5\uB85C\uB4DC \uACBD\uB85C \uC124\uC815
# \uB85C\uCEEC \uD14C\uC2A4\uD2B8\uC6A9 (\uD504\uB85C\uC81D\uD2B8 \uD3F4\uB354 \uB0B4 uploads \uD3F4\uB354)
file.upload-dir=uploads