name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 20m
          script: |
            # 1. 루트 폴더(백엔드 및 컴포즈) 최신화
            cd ~/Insajang
            git fetch --all
            git reset --hard origin/master

            # 2. 프론트엔드 폴더 최신화
            cd ~/Insajang/insajang-frontend
            git fetch --all
            git reset --hard origin/master

            # 3. 파이썬 폴더 최신화
            cd ~/Insajang/insajang-python
            git fetch --all
            git reset --hard origin/main

            # 4. 순차 빌드를 통해 프리티어 메모리 고갈 방지 및 실행
            cd ~/Insajang
            docker compose build insajang-python
            docker compose build insajang-frontend
            docker compose build insajang-backend
            docker compose up -d
